name: Build Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    environment: ci
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./dist
          CLEAN: true
